CREATE TABLE bus_passes (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL,
email VARCHAR(50) NOT NULL,
pass_type VARCHAR(10) NOT NULL,
start_date DATE NOT NULL,
end_date DATE NOT NULL
);
